apiVersion: v1
data:
  keeper_config.xml: |
    <clickhouse>
      <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>0</server_id>
        <listen_host>0.0.0.0</listen_host>
        <interserver_listen_host>0.0.0.0</interserver_listen_host>
        <enable_ipv6>false</enable_ipv6>
        <raft_configuration>
          <server>
            <id>0</id>
            <hostname>clickhouse-keeper-0.clickhouse-keeper-headless.nhbank.svc.cluster.local</hostname>
            <port>9234</port>
          </server>
        </raft_configuration>
      </keeper_server>
    </clickhouse>
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: keeper
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: clickhouse
    app.kubernetes.io/version: 25.6.2
    helm.sh/chart: clickhouse-9.3.8
  name: clickhouse-keeper
  namespace: nhbank
