apiVersion: v1
data:
  otel-collector-config.yaml: "receivers:\n  otlp:\n    protocols:\n      grpc:\n
    \       endpoint: 0.0.0.0:4317\n      http:\n        endpoint: 0.0.0.0:4318\n
    \       cors:\n          allowed_origins:\n          - http://*\n          - https://*\n
    \         allowed_headers:\n          - \"*\"\n\nprocessors:\n  imqaconsoleprintprocessor:\n
    \   trace_enabled: false\n    log_enabled: false      \n  imqaserviceprocessor:\n
    \   api_endpoint: https://nhbank.imqa.io/api/v1/services\n    enabled: false\n
    \   # service_data_fetch_interval must be at least 60 seconds\n    service_data_fetch_interval:
    60s\n    use_insecure: true\n  imqaattributeprocessor:\n    api_endpoint: https://nhbank.imqa.io/api/v1/screens\n
    \   enabled: true\n    # group_data_fetch_interval must be at least 60 seconds\n
    \   group_data_fetch_interval: 60s\n    use_insecure: true\n  batch:\n    send_batch_size:
    10000\n    send_batch_max_size: 11000\n    timeout: 10s\n\n\n  memory_limiter:\n
    \   # 80% of maximum memory up to 2G\n    limit_mib: 1500 # 25% of limit up to
    2G\n    spike_limit_mib: 512\n    check_interval: 5s # 50% of the maximum memory\n
    \   limit_percentage: 50 # 20% of max memory usage spike expected\n    spike_limit_percentage:
    20\n\nextensions:\n  health_check:\n    endpoint: 0.0.0.0:13133\n  zpages:\n    endpoint:
    0.0.0.0:55679\n  pprof:\n    endpoint: 0.0.0.0:1777\n\nexporters:\n  clickhousetraces:\n
    \   datasource: tcp://default:e0rdBg86jm@clickhouse.nhbank.svc.cluster.local:9000/imqa_traces\n
    \   docker_multi_node_cluster: false\n    low_cardinal_exception_grouping: false\n\n\n
    \ clickhouselogsexporterv2:\n    endpoint: tcp://default:e0rdBg86jm@clickhouse.nhbank.svc.cluster.local:9000
    \   \n    database: imqa_logs\n    logs_table_name: logs_v2   \n    create_schema:
    false\n    timeout: 10s\n    retry_on_failure:\n      enabled: true\n      initial_interval:
    5s\n      max_interval: 30s\n      max_elapsed_time: 300s\n  otlphttp:\n    traces_endpoint:
    http://otel-collector-symbolicator:4319/v1/traces\n    logs_endpoint: http://otel-collector-symbolicator:4319/v1/logs\n
    \   # traces_endpoint: http://otel-collector-symbolicator:4319/v1/traces\n    encoding:
    json\n\nservice:\n  telemetry:\n    metrics:\n      level: none        \n      address:
    0.0.0.0:8888\n  extensions:\n  - health_check\n  - zpages\n  - pprof\n  \n  pipelines:\n\n
    \   traces:\n      receivers: [ otlp ]\n      processors: [ imqaconsoleprintprocessor,
    memory_limiter, imqaserviceprocessor, imqaattributeprocessor, batch ]\n      exporters:
    [ clickhousetraces, otlphttp ]\n\n    logs:\n      receivers: [ otlp ]\n      processors:
    [ imqaconsoleprintprocessor, memory_limiter, imqaserviceprocessor, imqaattributeprocessor,
    batch ]\n      exporters: [ clickhouselogsexporterv2, otlphttp ]          \n"
kind: ConfigMap
metadata:
  annotations:
  name: otel-collector-config
  namespace: nhbank
