apiVersion: v1
data:
  admin-password: ZTByZEJnODZqbQ==
kind: Secret
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: clickhouse
    app.kubernetes.io/version: 25.6.2
    helm.sh/chart: clickhouse-9.3.8
  name: clickhouse
  namespace: nhbank

type: Opaque
