apiVersion: v1
data:
  ClickHouseUrl: dGNwOi8vZGVmYXVsdDplMHJkQmc4NmptQGNsaWNraG91c2UubmhiYW5rLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDA=
kind: Secret
metadata:
  annotations:
  name: clickhouse-secrets
  namespace: nhbank

type: Opaque
