apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
  labels:
    app: imqa-api
    pod-template-hash: 6c95d877d4
  name: imqa-api-6c95d877d4
  namespace: nhbank
  ownerReferences:
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: imqa-api

spec:
  replicas: 0
  selector:
    matchLabels:
      app: imqa-api
      pod-template-hash: 6c95d877d4
  template:
    metadata:
      labels:
        app: imqa-api
        pod-template-hash: 6c95d877d4
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secret
        image: imqav3.azurecr.io/imqa-api:1.4.0-rc.1.4
        imagePullPolicy: Always
        name: imqa-api
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8085
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data-volume
